version: "3.9"
services:
  reddit-place-2022:
    image: "denverquane/reddit-place-2022:main"
    environment:
      PLACE_DATA_DIR: /app/data
    volumes:
      - place-data:/app/data
      - place-images:/app/images

volumes:
  place-data:
  place-images: